<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<VersionPrefix>1.0.2</VersionPrefix>
		<Authors>LFDCC</Authors>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AssemblyName>Modbus</AssemblyName>
		<PackageId>LFDCC.Modbus</PackageId>
		<PackageTags>modbus;tcp;udp;rtu;client;server;coreclr</PackageTags>
		<PackageProjectUrl>https://github.com/LFDCC/Modbus</PackageProjectUrl>
		<NoWarn>1701;1702;1705;1591;NETSDK1138</NoWarn>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="TouchSocket" Version="4.2.18" />
	  <PackageReference Include="TouchSocket.SerialPorts" Version="4.2.18" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\LICENSE.txt" Pack="true" PackagePath="\" />
	  <None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
