<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Example.WriteMultipleRegisters - FC16 写多个寄存器示例</Description>
    <TargetFramework>net6.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>NETSDK1138</NoWarn>
    <AssemblyName>Example.WriteMultipleRegisters</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Example.WriteMultipleRegisters</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modbus\Modbus.csproj" />
  </ItemGroup>
</Project>
